name: Build & Push

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: crpi-ytlg6tfv9wxn5mfu.cn-shanghai.personal.cr.aliyuncs.com
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            crpi-ytlg6tfv9wxn5mfu.cn-shanghai.personal.cr.aliyuncs.com/mxy-x/taskflow-backend:latest
            crpi-ytlg6tfv9wxn5mfu.cn-shanghai.personal.cr.aliyuncs.com/mxy-x/taskflow-backend:${{ github.sha }}
